# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyGym' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyGym
pod 'TweeTextField'



  target 'MyGymTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyGymUITests' do
    # Pods for testing
  end

end
